name: build & release

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build UI bundle
      run: npx gulp bundle

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ui-bundle
        path: build/ui-bundle.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1.20.0
      with:
        artifacts: "build/ui-bundle.zip"
        artifactContentType: "application/zip"
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
